# Generated by Django 4.2.3 on 2023-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_bookingmanager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bookingsettings",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
